add cfs-base dockerfile
Signed-off-by: zhuzhengyi1 <zhuzhengyi@jd.com>

diff --git a/docker/docker-compose.yml b/docker/docker-compose.yml
--- a/docker/docker-compose.yml
+++ b/docker/docker-compose.yml
@@ -9,7 +9,7 @@ networks:
 
 services:
     servers:
-        image: chubaofs/cfs-build:1.0
+        image: chubaofs/cfs-base:1.0
         depends_on:
             - master1
             - master2
@@ -25,7 +25,7 @@ services:
             extnetwork:
 
     master1:
-        image: chubaofs/cfs-build:1.0
+        image: chubaofs/cfs-base:1.0
         ports:
             - "5901"
             - "5902"
@@ -42,7 +42,7 @@ services:
                 ipv4_address: 192.168.0.11
 
     master2:
-        image: chubaofs/cfs-build:1.0
+        image: chubaofs/cfs-base:1.0
         ports:
             - "5901"
             - "5902"
@@ -58,7 +58,7 @@ services:
             extnetwork:
                 ipv4_address: 192.168.0.12
     master3:
-        image: chubaofs/cfs-build:1.0
+        image: chubaofs/cfs-base:1.0
         ports:
             - "5901"
             - "5902"
@@ -75,7 +75,7 @@ services:
                 ipv4_address: 192.168.0.13
 
     metanode1:
-        image: chubaofs/cfs-build:1.0
+        image: chubaofs/cfs-base:1.0
         ports:
             - "17210"
             - "17220"
@@ -95,7 +95,7 @@ services:
             - "master3"
 
     metanode2:
-        image: chubaofs/cfs-build:1.0
+        image: chubaofs/cfs-base:1.0
         ports:
             - "17210"
             - "17220"
@@ -114,7 +114,7 @@ services:
             - "master2"
             - "master3"
     metanode3:
-        image: chubaofs/cfs-build:1.0
+        image: chubaofs/cfs-base:1.0
         ports:
             - "17210"
             - "17220"
@@ -134,7 +134,7 @@ services:
             - "master3"
 
     datanode1:
-        image: chubaofs/cfs-build:1.0
+        image: chubaofs/cfs-base:1.0
         ports:
             - "17310"
             - "17320"
@@ -154,7 +154,7 @@ services:
         networks:
             extnetwork:
     datanode2:
-        image: chubaofs/cfs-build:1.0
+        image: chubaofs/cfs-base:1.0
         ports:
             - "17310"
             - "17320"
@@ -174,7 +174,7 @@ services:
         networks:
             extnetwork:
     datanode3:
-        image: chubaofs/cfs-build:1.0
+        image: chubaofs/cfs-base:1.0
         ports:
             - "17310"
             - "17320"
@@ -186,16 +186,12 @@ services:
             - ./conf/datanode.json:/cfs/conf/datanode.json
             - ./script/start_datanode.sh:/cfs/script/start.sh
         command: /bin/sh /cfs/script/start.sh
-        depends_on:
-            - "metanode1"
-            - "metanode2"
-            - "metanode3"
         restart: on-failure
         networks:
             extnetwork:
 
     datanode4:
-        image: chubaofs/cfs-build:1.0
+        image: chubaofs/cfs-base:1.0
         ports:
             - "17310"
             - "17320"
@@ -207,18 +203,13 @@ services:
             - ./conf/datanode.json:/cfs/conf/datanode.json
             - ./script/start_datanode.sh:/cfs/script/start.sh
         command: /bin/sh /cfs/script/start.sh
-        depends_on:
-            - "metanode1"
-            - "metanode2"
-            - "metanode3"
         restart: on-failure
         networks:
             extnetwork:
 
     client:
-        image: chubaofs/centos-ltp:1.0
+        image: chubaofs/cfs-base:1.0
         volumes:
-            - .:/go/src/github.com/chubaofs/cfs
             - ./bin:/cfs/bin
             - ./conf/client.json:/cfs/conf/client.json
             - ./script/run_test.sh:/cfs/script/start.sh
@@ -232,5 +223,22 @@ services:
         security_opt:
             - "apparmor:unconfiged"
         command: /bin/bash /cfs/script/start.sh
+        networks:
+            extnetwork:
+
+    build:
+        image: chubaofs/cfs-base:1.0
+        volumes:
+            - ../:/go/src/github.com/chubaofs/chubaofs
+        command:
+            - bash
+            - "-c"
+            - >-
+              set -e;
+              mkdir -p /go/src/github.com/chubaofs/chubaofs/docker/bin &&
+              echo -n 'build server ' ;
+              cd /go/src/github.com/chubaofs/chubaofs/cmd && bash ./build.sh && mv cmd /go/src/github.com/chubaofs/chubaofs/docker/bin/cfs-server && echo "success" || echo "failed" ;
+              echo -n 'build client ' ;
+              cd /go/src/github.com/chubaofs/chubaofs/client && bash ./build.sh && mv client /go/src/github.com/chubaofs/chubaofs/docker/bin/cfs-client && echo 'success' || echo "failed" ;
         networks:
             extnetwork:
