update. go import path change from chubaofs to cubefs
Signed-off-by: leonrayang <chl696@sina.com>

diff --git a/docker/docker-compose-auth.yml b/docker/docker-compose-auth.yml
--- a/docker/docker-compose-auth.yml
+++ b/docker/docker-compose-auth.yml
@@ -324,11 +324,11 @@ services:
       - "-c"
       - >-
         set -e;
-        mkdir -p /go/src/github.com/chubaofs/chubaofs/docker/bin &&
+        mkdir -p /go/src/github.com/cubefs/cubefs/docker/bin &&
         echo -n 'build server ' ;
-        cd /go/src/github.com/chubaofs/chubaofs/cmd && bash ./build.sh && mv cfs-server /go/src/github.com/chubaofs/chubaofs/docker/bin/cfs-server && echo "success" || echo "failed" ;
+        cd /go/src/github.com/cubefs/cubefs/cmd && bash ./build.sh && mv cfs-server /go/src/github.com/cubefs/cubefs/docker/bin/cfs-server && echo "success" || echo "failed" ;
         echo -n 'build client ' ;
-        cd /go/src/github.com/chubaofs/chubaofs/client && bash ./build.sh && mv cfs-client /go/src/github.com/chubaofs/chubaofs/docker/bin/cfs-client && echo 'success' || echo "failed" ;
+        cd /go/src/github.com/cubefs/cubefs/client && bash ./build.sh && mv cfs-client /go/src/github.com/cubefs/cubefs/docker/bin/cfs-client && echo 'success' || echo "failed" ;
     networks:
       authnode_extnetwork:
 
@@ -341,7 +341,7 @@ services:
       - "-c"
       - >-
         set -e;
-        mkdir -p /go/src/github.com/chubaofs/chubaofs/docker/bin &&
+        mkdir -p /go/src/github.com/cubefs/cubefs/docker/bin &&
         cd /go/src/github.com/chubaofs/chubaofs && make test
     networks:
       authnode_extnetwork:
