add go mod
Signed-off-by: zhuzhengyi1 <zhuzhengyi@jd.com>

diff --git a/docker/docker-compose.yml b/docker/docker-compose.yml
--- a/docker/docker-compose.yml
+++ b/docker/docker-compose.yml
@@ -237,8 +237,8 @@ services:
               set -e;
               mkdir -p /go/src/github.com/chubaofs/chubaofs/docker/bin &&
               echo -n 'build server ' ;
-              cd /go/src/github.com/chubaofs/chubaofs/cmd && bash ./build.sh && mv cmd /go/src/github.com/chubaofs/chubaofs/docker/bin/cfs-server && echo "success" || echo "failed" ;
+              cd /go/src/github.com/chubaofs/chubaofs/cmd && bash ./build.sh && mv cfs-server /go/src/github.com/chubaofs/chubaofs/docker/bin/cfs-server && echo "success" || echo "failed" ;
               echo -n 'build client ' ;
-              cd /go/src/github.com/chubaofs/chubaofs/client && bash ./build.sh && mv client /go/src/github.com/chubaofs/chubaofs/docker/bin/cfs-client && echo 'success' || echo "failed" ;
+              cd /go/src/github.com/chubaofs/chubaofs/client && bash ./build.sh && mv cfs-client /go/src/github.com/chubaofs/chubaofs/docker/bin/cfs-client && echo 'success' || echo "failed" ;
         networks:
             extnetwork:
