Fix: fix docker ip address and format configuration files
Signed-off-by: Mervin <mofei2816@gmail.com>

diff --git a/docker/docker-compose.yml b/docker/docker-compose.yml
--- a/docker/docker-compose.yml
+++ b/docker/docker-compose.yml
@@ -47,7 +47,7 @@ services:
             - "17020"
             - 9500
         volumes:
-            - ./bin:/cfs/bin
+            - ./bin:/cfs/bin:ro
             - ./conf/master1.json:/cfs/conf/master.json
             - ./script/start_master.sh:/cfs/script/start.sh
         command: /bin/sh /cfs/script/start.sh
@@ -66,7 +66,7 @@ services:
             - "17020"
             - 9500
         volumes:
-            - ./bin:/cfs/bin
+            - ./bin:/cfs/bin:ro
             - ./conf/master2.json:/cfs/conf/master.json
             - ./script/start_master.sh:/cfs/script/start.sh
         command: /bin/sh /cfs/script/start.sh
@@ -84,7 +84,7 @@ services:
             - "17020"
             - 9500
         volumes:
-            - ./bin:/cfs/bin
+            - ./bin:/cfs/bin:ro
             - ./conf/master3.json:/cfs/conf/master.json
             - ./script/start_master.sh:/cfs/script/start.sh
         command: /bin/sh /cfs/script/start.sh
@@ -103,7 +103,7 @@ services:
             - "17240"
             - 9500
         volumes:
-            - ./bin:/cfs/bin
+            - ./bin:/cfs/bin:ro
             - ./conf/metanode.json:/cfs/conf/metanode.json
             - ./script/start_meta.sh:/cfs/script/start.sh
         command: /bin/bash /cfs/script/start.sh
@@ -122,7 +122,7 @@ services:
             - "17240"
             - 9500
         volumes:
-            - ./bin:/cfs/bin
+            - ./bin:/cfs/bin:ro
             - ./conf/metanode.json:/cfs/conf/metanode.json
             - ./script/start_meta.sh:/cfs/script/start.sh
         command: /bin/bash /cfs/script/start.sh
@@ -141,7 +141,7 @@ services:
             - "17240"
             - 9500
         volumes:
-            - ./bin:/cfs/bin
+            - ./bin:/cfs/bin:ro
             - ./conf/metanode.json:/cfs/conf/metanode.json
             - ./script/start_meta.sh:/cfs/script/start.sh
         command: /bin/bash /cfs/script/start.sh
@@ -160,7 +160,7 @@ services:
                 - "17240"
                 - 9500
             volumes:
-                - ./bin:/cfs/bin
+                - ./bin:/cfs/bin:ro
                 - ./conf/metanode.json:/cfs/conf/metanode.json
                 - ./script/start_meta.sh:/cfs/script/start.sh
             command: /bin/bash /cfs/script/start.sh
@@ -180,7 +180,7 @@ services:
             - 9500
         volumes:
             - ${DiskPath:-./disk}/1:/cfs/disk
-            - ./bin:/cfs/bin
+            - ./bin:/cfs/bin:ro
             - ./conf/datanode.json:/cfs/conf/datanode.json
             - ./script/start_datanode.sh:/cfs/script/start.sh
         command: /bin/bash /cfs/script/start.sh
@@ -200,7 +200,7 @@ services:
             - 9500
         volumes:
             - ${DiskPath:-./disk}/2:/cfs/disk
-            - ./bin:/cfs/bin
+            - ./bin:/cfs/bin:ro
             - ./conf/datanode.json:/cfs/conf/datanode.json
             - ./script/start_datanode.sh:/cfs/script/start.sh
         command: /bin/sh /cfs/script/start.sh
@@ -220,7 +220,7 @@ services:
             - 9500
         volumes:
             - ${DiskPath:-./disk}/3:/cfs/disk
-            - ./bin:/cfs/bin
+            - ./bin:/cfs/bin:ro
             - ./conf/datanode.json:/cfs/conf/datanode.json
             - ./script/start_datanode.sh:/cfs/script/start.sh
         command: /bin/sh /cfs/script/start.sh
@@ -240,7 +240,7 @@ services:
             - 9500
         volumes:
             - ${DiskPath:-./disk}/4:/cfs/disk
-            - ./bin:/cfs/bin
+            - ./bin:/cfs/bin:ro
             - ./conf/datanode.json:/cfs/conf/datanode.json
             - ./script/start_datanode.sh:/cfs/script/start.sh
         command: /bin/sh /cfs/script/start.sh
@@ -255,7 +255,7 @@ services:
         ports:
             - "80"
         volumes:
-            - ./bin:/cfs/bin
+            - ./bin:/cfs/bin:ro
             - ./conf/objectnode.json:/cfs/conf/objectnode.json
             - ./script/start_objectnode.sh:/cfs/script/start.sh
         command: /bin/sh /cfs/script/start.sh
@@ -270,7 +270,7 @@ services:
         ports:
             - "80"
         volumes:
-            - ./bin:/cfs/bin
+            - ./bin:/cfs/bin:ro
             - ./conf/objectnode.json:/cfs/conf/objectnode.json
             - ./script/start_objectnode.sh:/cfs/script/start.sh
         command: /bin/sh /cfs/script/start.sh
@@ -285,7 +285,7 @@ services:
         ports:
             - "80"
         volumes:
-            - ./bin:/cfs/bin
+            - ./bin:/cfs/bin:ro
             - ./conf/objectnode.json:/cfs/conf/objectnode.json
             - ./script/start_objectnode.sh:/cfs/script/start.sh
         command: /bin/sh /cfs/script/start.sh
@@ -300,7 +300,7 @@ services:
         ports:
             - 9500
         volumes:
-            - ./bin:/cfs/bin
+            - ./bin:/cfs/bin:ro
             - ./conf/client.json:/cfs/conf/client.json
             - ./script/run_test.sh:/cfs/script/start.sh
             - ./script/start_client.sh:/cfs/script/start_client.sh
@@ -323,7 +323,7 @@ services:
         privileged: true
         networks:
             extnetwork:
-                ipv4_address: 192.168.0.100
+                ipv4_address: 192.168.0.101
 
     prometheus:
         image: prom/prometheus
@@ -334,7 +334,7 @@ services:
         privileged: true
         networks:
             extnetwork:
-                ipv4_address: 192.168.0.200
+                ipv4_address: 192.168.0.102
 
     grafana:
         image: grafana/grafana:6.2.0
@@ -350,6 +350,7 @@ services:
         #command: /bin/bash
         networks:
             extnetwork:
+                ipv4_address: 192.168.0.103
 
     nginx:
         image: nginx:1.17.8
@@ -362,7 +363,7 @@ services:
         privileged: true
         networks:
             extnetwork:
-                ipv4_address: 192.168.0.300
+                ipv4_address: 192.168.0.104
 
     build:
         image: chubaofs/cfs-base:1.0
@@ -375,9 +376,9 @@ services:
               set -e;
               mkdir -p /go/src/github.com/chubaofs/chubaofs/docker/bin &&
               echo -n 'build server ' ;
-              cd /go/src/github.com/chubaofs/chubaofs/cmd && bash ./build.sh && mv cfs-server /go/src/github.com/chubaofs/chubaofs/docker/bin/cfs-server && echo "success" || echo "failed" ;
+              cd /go/src/github.com/chubaofs/chubaofs/cmd && bash ./build.sh && mv cfs-server /go/src/github.com/chubaofs/chubaofs/docker/bin/cfs-server && echo "[success]" || echo "[failed]" ;
               echo -n 'build client ' ;
-              cd /go/src/github.com/chubaofs/chubaofs/client && bash ./build.sh && mv cfs-client /go/src/github.com/chubaofs/chubaofs/docker/bin/cfs-client && echo 'success' || echo "failed" ;
+              cd /go/src/github.com/chubaofs/chubaofs/client && bash ./build.sh && mv cfs-client /go/src/github.com/chubaofs/chubaofs/docker/bin/cfs-client && echo '[success]' || echo "[failed]" ;
         networks:
             extnetwork:
 
